{{- $originalContext := . -}}
{{- with .Values.enterprise -}}
{{- with .flinkK8sOperatorDeploymentManager -}}
{{- if .enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ default "flink-deployment-creator" .flinkDeploymentCreatorRole }}
  labels:
    {{ include "nussknacker.labels" $originalContext | nindent 4 }}
rules:
- apiGroups: ["flink.apache.org"]
  resources: ["flinkdeployments"]
  verbs: ["create", "delete", "list", "update", "get"]
{{- end }}
{{- end }}
{{- end }}