{{- if and (hasKey .Values "enterprise.flinkK8sOperatorDeploymentManager") .Values.enterprise.flinkK8sOperatorDeploymentManager.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "flink-service-account" .Values.enterprise.flinkK8sOperatorDeploymentManager.flinkServiceAccount }}
  labels:
    {{ include "nussknacker.labels" . | nindent 4 }}
{{- end -}}