{{- if and (hasKey .Values "flinkK8sOperatorDeploymentManager") .Values.flinkK8sOperatorDeploymentManager.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ default "flink-operator" .Values.flinkK8sOperatorDeploymentManager.flinkOperatorRole }}-rolebinding
  labels:
    {{ include "nussknacker.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ default "flink-service-account" .Values.flinkK8sOperatorDeploymentManager.flinkServiceAccount }}
roleRef:
  kind: Role
  name: {{ default "flink-operator" .Values.flinkK8sOperatorDeploymentManager.flinkOperatorRole }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}