{{- if and (hasKey .Values "flinkK8sOperator") .Values.flinkK8sOperator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink-operator-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
{{- end }}