{{- if and (hasKey .Values "flinkK8sOperatorDeploymentManager") .Values.flinkK8sOperatorDeploymentManager.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "flink-service-account" .Values.flinkK8sOperatorDeploymentManager.flinkServiceAccount }}
{{- end -}}