{{- $originalContext := . -}}
{{- with .Values.enterprise -}}
{{- with .flinkK8sOperatorDeploymentManager -}}
{{- if .enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ default "flink-deployment-creator" .flinkDeploymentCreatorRole }}-rolebinding
  labels:
    {{- include "nussknacker.labels" $originalContext | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "nussknacker.serviceAccountName" $originalContext }}
roleRef:
  kind: Role
  name: {{ default "flink-deployment-creator" .flinkDeploymentCreatorRole }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
{{- end }}