{{- if and (hasKey .Values "flink-k8s-operator") .Values.flink-k8s-operator.enabled }}
{{- if .Values.clusterRoleBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterRoleBinding.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.clusterRoleBinding.roleName }}
subjects:
{{- range .Values.clusterRoleBinding.subjects }}
- kind: ServiceAccount
  name: {{ .name }}
  namespace: {{ .namespace }}
{{- end }}
{{- end }}
{{- end }}