{{- if and (hasKey .Values "enterprise.flinkK8sOperatorDeploymentManager") .Values.enterprise.flinkK8sOperatorDeploymentManager.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ default "flink-deployment-creator" .Values.enterprise.flinkK8sOperatorDeploymentManager.flinkDeploymentCreatorRole }}-rolebinding
  labels:
    {{ include "nussknacker.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "nussknacker.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ default "flink-deployment-creator" .Values.enterprise.flinkK8sOperatorDeploymentManager.flinkDeploymentCreatorRole }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}