{{- with .Values.enterprise -}}
{{- with .flinkK8sOperatorDeploymentManager -}}
{{- if .enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ default "flink-operator" .flinkOperatorRole }}-rolebinding
  labels:
    {{ include "nussknacker.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ default "flink-service-account" .flinkServiceAccount }}
roleRef:
  kind: Role
  name: {{ default "flink-operator" .flinkOperatorRole }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
{{- end }}