{{- $originalContext := . -}}
{{- with .Values.enterprise -}}
{{- with .flinkK8sOperatorDeploymentManager -}}
{{- if .enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "flink-service-account" .flinkServiceAccount }}
  labels:
    {{ include "nussknacker.labels" $originalContext | nindent 4 }}
{{- end -}}
{{- end -}}
{{- end -}}