{{- if and (hasKey .Values "flinkK8sOperator") .Values.flinkK8sOperator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink-operator-rolebinding
subjects:
- kind: ServiceAccount
  name: flink-service-account
roleRef:
  kind: Role
  name: flink-operator-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}