{{- $originalContext := . -}}
{{- with .Values.enterprise -}}
{{- with .flinkK8sOperatorDeploymentManager -}}
{{- if .enabled }}
{{- with .jobJarStorage -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .pvcName }}
{{- if and (hasKey . "keepAfterUninstall") .keepAfterUninstall }}
  annotations:
    "helm.sh/resource-policy": keep
{{- end }}
  labels:
    {{ include "nussknacker.labels" $originalContext | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ default "1Gi" .pvcSize }}
  {{- with .pvcStorageClassName }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}