{{- if and (hasKey .Values "flinkK8sOperator") .Values.flinkK8sOperator.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-flinkdeployments
  labels:
    {{ include "nussknacker.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{ include "nussknacker.labels" . | nindent 8 }}
    spec:
      serviceAccountName: nussknacker
      containers:
        - name: delete-flinkdeployments
          image: bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              kubectl delete flinkdeployments --all -n {{ .Release.Namespace }}
          resources:
            limits:
              cpu: "100m"
              memory: "30Mi"
            requests:
              cpu: "100m"
              memory: "30Mi"
      restartPolicy: Never
  backoffLimit: 1
{{- end }}
