{{- if and (hasKey .Values "flinkK8sOperator") .Values.flinkK8sOperator.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-flinkdeployments
  labels:
{{ include "nussknacker.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: delete-flinkdeployments
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              kubectl delete flinkdeployments --all -n {{ .Release.Namespace }}
      restartPolicy: Never
  backoffLimit: 1
{{- end }}