{{- if .Values.flink-k8s-operator.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payload-pvc-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
{{- end }}