{{- if and (hasKey .Values "flinkK8sOperator") .Values.flinkK8sOperator.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payload-pvc-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
{{- end }}