include:
  - project: 'carpinion/ci/templates'
    file: 'vanilla-helm.yaml'

build:
  script:
    - helm repo add stable https://kubernetes-charts.storage.googleapis.com/
    - helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
    - helm repo add riskfocus https://riskfocus.github.io/helm-charts-public/
    - helm repo add touk https://helm-charts.touk.pl/public/
    - helm dependencies build ./src
    - helm package ./src -d dist --version $VERSION

deploy:
  services:
    - docker:dind
  script:
    - docker info | grep Driver
    - env
    - kubectl get secret "$CI_ENVIRONMENT_SLUG-postgresql" || kubectl create secret generic "$CI_ENVIRONMENT_SLUG-postgresql" --from-literal postgresql-password=`date +%s | sha256sum | base64 | head -c 32`
    - helm upgrade -i --devel "$CI_ENVIRONMENT_SLUG" ./dist/$NAME-$VERSION.tgz --set postgresql.existingSecret="$CI_ENVIRONMENT_SLUG-postgresql" -f deploy-values.yaml
