include:
  - project: 'carpinion/ci/templates'
    file: 'vanilla-helm.yaml'

build:
  script:
    - helm repo add stable https://kubernetes-charts.storage.googleapis.com/
    - helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
    - helm repo add riskfocus https://riskfocus.github.io/helm-charts-public/
    - helm repo add touk $CHARTS_PUBLIC_RELEASES_URL
    - helm repo add touk-private $CHARTS_PRIVATE_RELEASES_URL
    - helm repo add touk-snapshots $CHARTS_PRIVATE_SNAPSHOTS_URL
    - helm repo add influxdata https://helm.influxdata.com/
    - helm repo add grafana https://grafana.github.io/helm-charts
    - helm dependencies build ./src
    - helm package ./src -d dist --version $VERSION

deploy:
  services:
    - docker:dind
  script:
    - kubectl get secret "$CI_ENVIRONMENT_SLUG-postgresql" || kubectl create secret generic "$CI_ENVIRONMENT_SLUG-postgresql" --from-literal postgresql-password=`date +%s | sha256sum | base64 | head -c 32`
    - |
      helm upgrade -i --wait --devel "$CI_ENVIRONMENT_SLUG" touk/$NAME --version $VERSION \
        --set postgresql.existingSecret="$CI_ENVIRONMENT_SLUG-postgresql" \
        -f deploy-values.yaml
