image:
  pullPolicy: Always
  # FIXME abr remove
  #  tag: staging-latest
  tag: 1.19.0-preview_k8s-dm-classpath-fix-2025-02-25-23076-05f409f76-SNAPSHOT

imagePullSecrets:
  - name: gitlab-registry

resources:
  limits:
    memory: 1Gi
  requests:
    memory: 512Mi

ingress:
  enabled: true
  skipHost: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

kafka:
  replicas: 1

flink:
  taskmanager:
    replicaCount: 1
    #to be able to do anything...
    numberOfTaskSlots: 4
    resources:
      limits:
        memory: 3Gi
      requests:
        memory: 2560Mi

nussknacker:
  modelConfig:
    namespace: "{{ .Release.Name }}"
    components:
       openAPI:
         #TODO: find working OpenAPI 3.0 definition
         url: "https://app.swaggerhub.com/apiproxy/registry/TKJ/CurrencyConverter/FINAL"
  usageStatisticsReports: false

extraEnv:
  - name: NUSSKNACKER_LOG_LEVEL
    value: DEBUG
