image:
  pullPolicy: Always

nussknacker:
  mode: "lite-k8s"
  streaming:
    enabled: false

flink:
  enabled: false

kafka:
  enabled: false

apicurio-registry:
  enabled: false

zookeeper:
  enabled: false

telegraf:
  enabled: false
