image:
  repository: touk/nussknacker
  tag: staging-latest
  pullPolicy: Always

imagePullSecrets:
  - name: gitlab-registry

resources:
  limits:
    memory: 1Gi
  requests:
    memory: 512Mi

persistence:
  accessMode: ReadWriteMany
  storageClass: nfs

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  domain: carpinion.touk.pl

hermes:
  enabled: true
  imagePullSecrets:
    - name: gitlab-registry
  management:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      domain: carpinion.touk.pl
  frontend:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      domain: carpinion.touk.pl
  kafka:
    namespace: "{{ .Release.Name }}"

kafka:
  replicas: 1
  zookeeper:
    replicaCount: 1

flink:
  taskmanager:
    replicaCount: 1
    #zeby cokolwiek dalo sie zrobic ...
    numberOfTaskSlots: 4
    resources:
      limits:
        memory: 3Gi
      requests:
        memory: 2560Mi

nussknacker:
  modelConfig:
    namespace: "{{ .Release.Name }}"
#TODO: problem z wersja commons-io, konieczny upgrade NK... :/
#    openapi:
#      - url: "https://rdb-simpledb.restdb.io/rest/_swagger.json"
#        security:
#          apikey:
#            type: "apiKey"
#            apiKeyValue: "560bd47058e7ab1b2648f4e7"

telegraf:
  enabled: true

influxdb:
  enabled: true

grafana:
  enabled: true

schema-registry:
  enabled: true
  kafka:
    enabled: false
