image:
  tag: preview-req-resp-k8s-dm #todo change to staging-latest
  pullPolicy: Always

imagePullSecrets:
  - name: gitlab-registry

resources:
  limits:
    memory: 1Gi
  requests:
    memory: 512Mi

ingress:
  enabled: true
  skipHost: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

zookeeper:
  replicaCount: 1

kafka:
  replicas: 1

flink:
  taskmanager:
    replicaCount: 1
    #to be able to do anything...
    numberOfTaskSlots: 4
    resources:
      limits:
        memory: 3Gi
      requests:
        memory: 2560Mi

nussknacker:
  modelConfig:
    namespace: "{{ .Release.Name }}"
    components:
       openAPI:
         #TODO: find working OpenAPI 3.0 definition
         url: "https://app.swaggerhub.com/apiproxy/registry/TKJ/CurrencyConverter/FINAL"
       kafka:
         config:
           schemaRegistryCacheConfig:
             availableSchemasExpirationTime: 0 seconds

extraEnv:
  - name: NUSSKNACKER_LOG_LEVEL
    value: DEBUG

telegraf:
  enabled: true

influxdb:
  enabled: true

grafana:
  enabled: true

apicurio-registry:
  enabled: true
