image:
  pullPolicy: Always

imagePullSecrets:
  - name: gitlab-registry

persistence:
  accessMode: ReadWriteMany
  storageClass: nfs

kafka:
  replicas: 1
  zookeeper:
    replicaCount: 1

hermes:
  kafka:
    namespace: '{{ .Release.Name }}'

flink:
  taskmanager:
    replicaCount: 1
    resources:
      limits:
        memory: 3Gi
      requests:
        memory: 2560Mi

elasticsearch:
  master:
    replicas: 2
  data:
    replicas: 1
  client:
    replicas: 1

grafana:
  enabled: false
  rbac:
    create: false
    namespaced: true
    pspEnabled: false
resources:
  limits:
    memory: 1Gi
  requests:
    memory: 512Mi
schema-registry:
  enabled: true
  kafka:
    enabled: false
