image:
  pullPolicy: Always

imagePullSecrets:
  - name: gitlab-registry

resources:
  limits:
    memory: 1Gi
  requests:
    memory: 512Mi

persistence:
  accessMode: ReadWriteMany
  storageClass: nfs

hermes:
  enabled: true
  imagePullSecrets:
    - name: gitlab-registry
  management:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      domain: carpinion.touk.pl
  frontend:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      domain: carpinion.touk.pl
  kafka:
    namespace: "{{ .Release.Name }}"

kafka:
  replicas: 1
  zookeeper:
    replicaCount: 1

flink:
  taskmanager:
    replicaCount: 1
    resources:
      limits:
        memory: 3Gi
      requests:
        memory: 2560Mi

elasticsearch:
  enabled: false
  master:
    replicas: 2
  data:
    replicas: 1
  client:
    replicas: 1

telegraf:
  image:
    repo: docker-gitlab.touk.pl/carpinion/nussknacker/telegraf-influxdb2-plugin
    tag: master
  imagePullSecrets:
    - name: gitlab-registry
  args: [ "--config-directory", "/etc/telegraf/telegraf.d", "--plugin-directory", "/usr/lib/telegraf/plugins/" ]
  volumes:
    - name: additional-config
      configMap:
        name: ""
  volumeMounts:
    - name: additional-config
      mountPath: /etc/telegraf/telegraf.d

influxdb:
  enabled: false

grafana:
  enabled: false
  rbac:
    create: false
    namespaced: true
    pspEnabled: false

kibana:
  enabled: false

logstash:
  enabled: false

schema-registry:
  enabled: true
  kafka:
    enabled: false

#openapi:
#  url: "https://rdb-simpledb.restdb.io/rest/_swagger.json"
#  apikey: "560bd47058e7ab1b2648f4e7"
