image:
  pullPolicy: Always

flink:
  enabled: false

nussknacker:
  streaming:
    deploymentMode: "lite-k8s"

telegraf:
  enabled: false

zookeeper:
  enabled: false

kafka:
  kraft:
    enabled: true
  externalZookeeper:
    servers: []

