image:
  pullPolicy: Always

imagePullSecrets:
  - name: gitlab-registry

resources:
  limits:
    memory: 1Gi
  requests:
    memory: 512Mi

persistence:
  accessMode: ReadWriteMany
  storageClass: nfs

hermes:
  imagePullSecrets:
    - name: gitlab-registry
  management:
    ingress:
      enabled: true
      annotations:
        certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
      domain: carpinion.touk.pl
  frontend:
    ingress:
      enabled: true
      annotations:
        certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
      domain: carpinion.touk.pl

kafka:
  replicas: 1
  zookeeper:
    replicaCount: 1

hermes:
  kafka:
    namespace: "{{ .Release.Name }}"

flink:
  taskmanager:
    replicaCount: 1
    resources:
      limits:
        memory: 3Gi
      requests:
        memory: 2560Mi

elasticsearch:
  enabled: false
  master:
    replicas: 2
  data:
    replicas: 1
  client:
    replicas: 1

influxdb:
  enabled: false

grafana:
  enabled: false
  rbac:
    create: false
    namespaced: true
    pspEnabled: false

kibana:
  enabled: false

logstash:
  logstashJavaOpts: "-Xmx1g -Xms1g -XX:-AssumeMP"
schema-registry:
  enabled: true
  kafka:
    enabled: false

openapi:
  url: "https://rdb-simpledb.restdb.io/rest/_swagger.json"
  apikey: "560bd47058e7ab1b2648f4e7"
