persistence:
  enabled: true
  size: 100Mi
  accessMode: ReadWriteOnce

statefulSet:
  enabled: true

db:
  driver: 'org.hsqldb.jdbc.JDBCDriver'
  url: 'jdbc:hsqldb:file:/opt/nussknacker/storage/db?sql.syntax_ora=true'
  user: sa
  schema: PUBLIC

postgresql:
  enabled: false
