image:
  tag: staging-latest
  pullPolicy: Always

imagePullSecrets:
  - name: gitlab-registry

resources:
  limits:
    memory: 1Gi
  requests:
    memory: 512Mi

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  domain: carpinion.touk.pl

hermes:
  enabled: true
  imagePullSecrets:
    - name: gitlab-registry
  management:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      domain: carpinion.touk.pl
  frontend:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      domain: carpinion.touk.pl
  kafkaNamespace: "{{ .Release.Name }}"

zookeeper:
  replicaCount: 1

kafka:
  replicas: 1

flink:
  taskmanager:
    replicaCount: 1
    #to be able to do anything...
    numberOfTaskSlots: 4
    resources:
      limits:
        memory: 3Gi
      requests:
        memory: 2560Mi

nussknacker:
  modelConfig:
    namespace: "{{ .Release.Name }}"
    components:
       openAPI:
         #TODO: find working OpenAPI 3.0 definition
         url: "https://app.swaggerhub.com/apiproxy/registry/TKJ/CurrencyConverter/FINAL"

telegraf:
  enabled: true

influxdb:
  enabled: true

grafana:
  enabled: true

apicurio-registry:
  enabled: true
