apiVersion: v1
kind: Secret
metadata:
  name: $RELEASE-postgresql
  namespace: $NAMESPACE
  labels:
    "app.kubernetes.io/managed-by": "Helm"
  annotations:
    "meta.helm.sh/release-namespace": $NAMESPACE
    "meta.helm.sh/release-name": $RELEASE
type: Opaque
data:
  postgres-password: $POSTGRES_PASSWORD