apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nussknacker.fullname" . }}
  labels:
    {{- include "nussknacker.labels" . | nindent 4 }}
data:
  application.conf: |-

    {{- with .Values.db }}
    db: {{ tpl (toJson .) $ }}
    {{- end }}
    db.password: ${?DB_PASSWORD}

    processTypes {
      "default": {
          engineConfig: {
             type: "flinkStreaming"
             {{/* Find easier way of passing it through values */}}
             restUrl: "{{ include "nussknacker.flinkJobManagerUrl" . }}"
             queryableStateProxyUrl: "{{ include "nussknacker.flinkTaskManagerUrl" . }}"
          } {{ tpl (.Values.nussknacker.flinkConfig | mustToJson) . }}

          modelConfig: {
            kafka {
              kafkaAddress: "{{ include "nussknacker.kafkaUrl" . }}"
              kafkaProperties {
                "schema.registry.url": "{{ include "nussknacker.schemaRegistryUrl" . }}"
              }
            }
          }{{ tpl ( mustToJson .Values.nussknacker.modelConfig ) . }}
      }
    }

    {{- if .Values.influxdb.enabled }}
    countsSettings: {{ include "nussknacker.influxDbConfig" .}}
    {{- end }}

    {{- if .Values.grafana.enabled }}
        metricsSettings: {
          url: "{{ include "nussknacker.grafanaUrl" .}}/dashboard/db/$dashboard?theme=dark&var-processName=$process&var-env="${environment}
          defaultDashboard: "flink-esp"
        }
    {{- end }}

    {{/* We have to iterate over first level to embed in .conf properly... */}}
    {{- range $key, $val := .Values.nussknacker.uiConfig }}
      {{ $key }}: {{ tpl ( mustToJson $val ) $ }}
    {{- end }}

    {{/* Find easier way of passing it through values */}}
    customTabs: [ {{ include "nussknacker.hermesUiManagementTab" . }} ] {{ tpl ( mustToJson (.Values.nussknacker.uiConfig.customTabs | default list) ) . }}

    #Due to bug in NK, akka settings are not taken from defaults: https://github.com/TouK/nussknacker/pull/1259
    akka {
       http {
         server {
           parsing.max-content-length = 300000000 #300MB
           # Longer mainly for invoking tests on processes
           request-timeout = 1 minute
         }
       }
    }


