apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nussknacker.fullname" . }}
  labels:
    {{- include "nussknacker.labels" . | nindent 4 }}
data:
  application.conf: |-
    base: { include "/opt/nussknacker/conf/base-application.conf" }

    base.flinkEngineConfig.restUrl: "{{ include "nussknacker.flinkJobManagerUrl" . }}"
    base.flinkEngineConfig.queryableStateProxyUrl: "{{ include "nussknacker.flinkTaskManagerUrl" . }}"
    base.streamingModelConfig.kafka {
      kafkaAddress: "{{ include "nussknacker.kafkaUrl" . }}"
      kafkaProperties {
        "schema.registry.url": "{{ include "nussknacker.schemaRegistryUrl" . }}"
      }
    }
    {{- with .Values.db }}
    base.db: {{ tpl (toJson .) $ }}
    {{- end }}
    base.jdbcServer.enabled: false
    base.schemaRegistryUrl: "{{ include "nussknacker.schemaRegistryUrl" . }}"

    environment: "demo"

    categoriesConfig {
      "Default": "hermes-model"
    }

    processTypes {
      "hermes-model": {
          engineConfig: ${base.flinkEngineConfig}
          modelConfig: {{ tpl ( mustToJson .Values.modelConfig ) . }} ${base.streamingModelConfig}
      }
    }

    environmentAlert: {
      content: "KUBERNETES ENVIRONMENT"
      cssClass: "indicator-green"
    }

    metricsSettings: {
      url: ${base.grafanaUrl}"/dashboard/db/$dashboard?theme=dark&var-processName=$process&var-env="${environment}
      defaultDashboard: "flink-esp"
      processingTypeToDashboard: {
        "hermes-model": "flink-esp"
      }
    }


    # TODO: lightbend config can't include files on root level - move nussknacker config on nk level and get rid of this below
    jdbcServer: ${base.jdbcServer}
    db: ${base.db}
    akka: ${base.akka}
    authentication: ${base.authentication}

    commentSettings: ${base.commentSettings}
    attachmentsPath: ${base.attachmentsPath}
    countsSettings: ${base.countsSettings}
    kibanaSettings: ${base.kibanaSettings}

    {{- if .Values.openapi }}
    base.streamingModelConfig.openapi: [{
      url: "{{ .Values.openapi.url }}"
      {{- if .Values.openapi.apikey }}
      security: {
        apikey: {
          type: "apiKey"
          apiKeyValue: "{{ .Values.openapi.apikey }}"
        }
      }
      {{- end }}
    }]
    {{- end }}

    {{- if .Values.hermes.enabled }}
    customTabs: [{
      name: "Hermes"
      url: "{{ include "hermes.management.svcExternalUrl" (dict "Chart" (dict "Name" "hermes") "Values" .Values.hermes "Release" .Release "Capabilities" .Capabilities) }}"
      id: "hermes"
    }]
    {{- end }}
