apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nussknacker.fullname" . }}
  labels:
    {{- include "nussknacker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nussknacker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "nussknacker.selectorLabels" . | nindent 8 }}
        {{- if .Values.additionalLabels }}
          {{- toYaml .Values.additionalLabels | nindent 8 -}}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "nussknacker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /etc/nussknacker
            {{- if .Values.persistence.enabled }}
            - name: storage
              mountPath: /opt/nussknacker/storage
              subPath: {{ .Values.persistence.subPath }}
            {{- end }}
            {{- if .Values.additionalVolumeMounts }}
              {{- toYaml .Values.additionalVolumeMounts | nindent 12 -}}
            {{- end }}
          env:
            #TODO: make it default in NK
            - name: JDK_JAVA_OPTIONS
              value: -Dconfig.override_with_env_vars=true
            - name: CONFIG_FILE
              value: {{ .Values.nussknacker.configFile }}
            - name: HELM_RELEASE_NAME
              value: {{ .Release.Name }}
            {{- if .Values.designerLogbackConfig }}
            - name: LOGBACK_FILE
              value: "/etc/nussknacker/logback.xml"
            {{- end }}
            {{- if .Values.runtimeLogbackConfig }}
            - name: RUNTIME_LOGBACK_FILE
              value: "/etc/nussknacker/runtime-logback.xml"
            {{- end }}
            {{- if .Values.prometheusMetrics.enabled }}
            - name: PROMETHEUS_METRICS_PORT
              value: {{ .Values.prometheusMetrics.port | quote }}
            {{- end }}
            {{- if .Values.postgresql.enabled }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: '{{- include "postgresql.secretName" .Subcharts.postgresql }}'
                  key: postgresql-password
            {{- end -}}
            {{- if .Values.extraEnv -}}
              {{- .Values.extraEnv | toYaml | nindent 12 -}}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            {{ if .Values.prometheusMetrics.enabled }}
            - name: prometheus
              containerPort: {{ .Values.prometheusMetrics.port }}
              protocol: TCP
            {{ end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: {{ .Values.deployment.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.deployment.livenessProbe.failureThreshold }}
          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: {{ .Values.deployment.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.deployment.startupProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.sidecarContainers -}}
        {{- toYaml .Values.sidecarContainers | nindent 8 -}}
      {{- end }}      
      volumes:
        - name: config
          configMap:
            name: {{ include "nussknacker.fullname" . }}
        {{- if .Values.additionalVolumes }}
          {{- toYaml .Values.additionalVolumes | nindent 8 -}}
        {{- end }}
        - name: storage
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "nussknacker.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
