{{- if .Values.imageCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nussknacker.fullname" . }}-docker-auth
  namespace: {{ template "nussknacker.namespace" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}
