{{- if .Values.grafana.enabled -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{- printf "%s-%s" .Release.Name "influx-grafana-datasource" | trunc 63 | trimSuffix "-" -}}"
  labels:
     grafana_datasource: "influx"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: influx
      type: influxdb
      access: proxy
      orgId: 1
      url: {{ include "nussknacker.influxUrl" .}}
      database: nussknacker
      basicAuth: true
      isDefault: true
      version: 1
      editable: false
      user: ${influxdb-user}
      password: ${influxdb-password}
{{- end }}
