apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nussknacker.serviceAccountName" . }}
  labels:
{{ include "nussknacker.labels" . | nindent 4 }}
subjects:
- kind: User
  name: system:serviceaccount:default:{{ include "nussknacker.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: {{ include "nussknacker.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io