{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "nussknacker.fullname" . }}
  namespace: {{ template "nussknacker.namespace" . }}
  labels:
{{ include "nussknacker.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "nussknacker.serviceAccountName" . }}
roleRef:
  kind: Role 
  apiGroup: rbac.authorization.k8s.io
  {{- if (not .Values.rbac.useExistingRole) }}
  name: {{ template "nussknacker.fullname" . }}
  {{- else }}
  name: {{ .Values.rbac.useExistingRole }}
  {{- end }}
{{- end }}
