{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nussknacker.serviceAccountName" . }}
  labels:
{{ include "nussknacker.labels" . | nindent 4 }}
{{- end -}}
