apiVersion: v1
kind: Service
metadata:
  name: {{ include "nussknacker.fullname" . }}
  labels:
    {{- include "nussknacker.labels" . | nindent 4 }}
  annotations:
  {{ if .Values.prometheusMetrics.enabled }}
    prometheus.io/port: {{ .Values.prometheusMetrics.servicePort | quote }}
    prometheus.io/scrape: "true"
  {{ end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{ if .Values.prometheusMetrics.enabled }}
    - port: {{ .Values.prometheusMetrics.servicePort }}
      name: prometheus
      targetPort: prometheus
      protocol: TCP
    {{ end }}
  selector:
    {{- include "nussknacker.selectorLabels" . | nindent 4 }}
