apiVersion: v1
kind: Service
metadata:
  name: {{ include "nussknacker.fullname" . }}
  labels:
    {{- include "nussknacker.labels" . | nindent 4 }}
  annotations:
  {{- range $k, $v := .Values.service.annotations }}
    {{ $k | indent 4 }}: {{ $v | quote }}
  {{ end }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{ if .Values.prometheusMetrics.enabled }}
    - port: {{ .Values.prometheusMetrics.port }}
      name: prometheus
      targetPort: prometheus
      protocol: TCP
    {{ end }}
  selector:
    {{- include "nussknacker.selectorLabels" . | nindent 4 }}
