{{- if .Values.telegraf.enabled -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-nussknacker
  labels:
    {{- include "nussknacker.labels" . | nindent 4 }}
data:
  nussknacker.conf: |-
    # Flink reporters for Prometheus or InfluxDB are somewhat limited:
    # - no possibility of adding own tags
    # - no possitility of removing Flink internal tags (like job_id, task_id, etc.)
    # - metric name has all tags encoded inside
    # NOTE: Prometheus has different field names than e.g. InfluxDB reporter, (count -> gauge, different percentile names, etc.)

    [global_tags]
      env = "{{ .Values.nussknacker.uiConfig.environment }}"

    #FIXME: handle case where Flink is disabled but telegraf *is* enabled

    {{- /* Workaround for backward compatibility, and we cannot put this template in default chart values. */ -}}
    {{- if .Values.telegraf.nussknacker.inputs }}
    {{ template "telegraf.nussknacker.inputs" .Values.telegraf.nussknacker.inputs }}
    {{- else }}
    [[inputs.prometheus]]
      kubernetes_label_selector = "app.kubernetes.io/name=flink"
      monitor_kubernetes_pods = true
      monitor_kubernetes_pods_method = "settings"
      monitor_kubernetes_pods_namespace = "{{ template "nussknacker.namespace" . }}"
      monitor_kubernetes_pods_port = 9999
    {{- end }}
    {{ template "telegraf.nussknacker.processors" .Values.telegraf.nussknacker.processors }}
    {{ template "telegraf.nussknacker.aggregators" .Values.telegraf.nussknacker.aggregators }}

    [[outputs.influxdb]]
      urls = ["{{ include "nussknacker.influxUrl" . }}"]
      skip_database_creation = true
      database = "{{ .Values.telegraf.influxdb.database | default "nussknacker" }}"
      {{- if .Values.telegraf.influxdb.username }}
      username = "{{ .Values.telegraf.influxdb.username }}"
      password = "{{ .Values.telegraf.influxdb.password }}"
      {{- end }}
    {{ template "telegraf.nussknacker.outputs" .Values.telegraf.nussknacker.outputs }}
{{- end }}
