apiVersion: v2
name: nussknacker
version: 0.1.0-SNAPSHOT
description: A Helm chart for Nussknacker
type: application
appVersion: staging-latest

dependencies:
  - name: postgresql
    version: ^8.3.0
    repository: "@stable"
    condition: postgresql.enabled
  - name: kafka
    version: ^0.20.8
    repository: "@incubator"
    condition: kafka.enabled
  - name: schema-registry
    version: ^1.1.9
    repository: "@incubator"
    condition: schema-registry.enabled
  - name: schema-registry-ui
    version: ^0.4.1
    repository: "@stable"
    condition: schema-registry-ui.enabled
  - name: flink
    version: 0.1.4
    repository: "@riskfocus"
    condition: flink.enabled
  - name: elasticsearch
    version: ^1.32.3
    repository: "@stable"
    condition: elasticsearch.enabled
  - name: kibana
    version: ^3.2.6
    repository: "@stable"
    condition: kibana.enabled
  - name: logstash
    version: ^2.4.0
    repository: "@stable"
    condition: logstash.enabled
  - name: grafana
    version: ^5.0.0
    repository: "@stable"
    condition: grafana.enabled
  - name: influxdb
    version: ^4.2.4
    repository: "@stable"
    condition: influxdb.enabled

