#This configuration shows how to add extraEnv to NU designer and specify k8sDeploymentConfig for k8s runtime container
#This assumes that secret nussknacker-secrets is previously created with 'kubectl apply -f secret.yaml'
flink:
  enabled: false

extraEnv:
  - name: CONFIG_FORCE_nussknacker_modelConfig_components_openAPI_security_apikey_apiKeyValue
    valueFrom:
      secretKeyRef:
        name: 'nussknacker-secrets'
        key: OPEN_API_KEY
nussknacker:
  mode: "streaming-lite"
  k8sDeploymentConfig:
    spec.template.spec.containers:
      - env:
          - name: CONFIG_FORCE_nussknacker_modelConfig_components_openAPI_security_apikey_apiKeyValue
            valueFrom:
              secretKeyRef:
                key: OPEN_API_KEY
                name: nussknacker-secrets
        name: runtime
        image: touk/nussknacker-lite-kafka-runtime:staging-latest
  modelConfig:
    components:
      openAPI:
        url: "https://litesecrettest-47e0.restdb.io/rest/_swagger.json"
        security:
          apikey:
            type: "apiKey"
            #this one is passed by secret which is binded to CONFIG_FORCE_ env
            apiKeyValue: "dummy value just for the sake designer need it at startup"

telegraf:
  enabled: false

kafka:
  enabled: true

influxdb:
  enabled: false

grafana:
  enabled: false

apicurio-registry:
  enabled: false

hermes:
  enabled: false