{
 "title": "RequestResponse scenario",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "scenarioName",
    "query": "SHOW TAG VALUES FROM \"invocation.success.histogram\" WITH KEY = \"scenario\""
   },
   {
    "name": "env",
    "query": "SHOW TAG VALUES FROM \"invocation.success.histogram\" WITH KEY = \"env\""
   },
   {
    "name": "interval",
    "query": "10s,30s,1m,3m, 10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Basics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Response 2xx - throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_nodeId]]",
     "query": "SELECT sum(value)\nFROM (\n  SELECT non_negative_derivative(last(\"count\"), 1s) AS value\n  FROM \"invocation.success.histogram\"\n  WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), scenario, nodeId, instanceId\n)\nGROUP BY time($__interval), scenario, nodeId\n"
    }
   ]
  },
  {
   "title": "Outputs/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_nodeId]]",
     "query": "SELECT sum(value)\nFROM (\n  SELECT non_negative_derivative(last(\"count\"), 1s) AS value\n  FROM \"end.count\"\n  WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), scenario, nodeId, instanceId\n)\nGROUP BY time($__interval), scenario, nodeId\n"
    },
    {
     "alias": "[[tag_scenario]] - [[tag_nodeId]]",
     "query": "SELECT sum(value)\nFROM (\n  SELECT non_negative_derivative(last(\"count\"), 1s) AS value\n  FROM \"dead_end.count\"\n  WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), scenario, nodeId, instanceId\n)\nGROUP BY time($__interval), scenario, nodeId\n"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_nodeId]]",
     "query": "SELECT sum(value)\nFROM (\n  SELECT non_negative_derivative(last(\"count\"), 1s) AS value\n  FROM \"error.instantRateByNode.count\"\n  WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), scenario, nodeId, instanceId\n)\nGROUP BY time($__interval), scenario, nodeId\n"
    }
   ]
  },
  {
   "title": "Response 2xx - median",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - (all)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "serviceName" ], "type": "tag" },
      { "params": [ "instanceId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "service.OK.histogram",
     "query": "SELECT max(\"p50\") FROM \"invocation.success.histogram\" WHERE (\"env\" =~ /^$env$/ AND \"scenario\" =~ /^$scenarioName$/) AND $timeFilter GROUP BY time($interval), \"scenario\", \"serviceName\" fill(null)",
     "select": [
      [
       { "params": [ "p50" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
     ]
    },
    {
     "alias": "[[tag_scenario]] - [[tag_serviceName]] (instanceId [[tag_instanceId]])",
     "query": "SELECT max(\"p50\") FROM \"invocation.success.histogram\" WHERE (\"env\" =~ /^$env$/ AND \"scenario\" =~ /^$scenarioName$/) AND $timeFilter GROUP BY time($interval), \"scenario\", \"serviceName\", \"instanceId\" fill(null)"
    }
   ]
  },
  {
   "title": "Response 2xx - median - 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - (all)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "serviceName" ], "type": "tag" },
      { "params": [ "instanceId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "service.OK.histogram",
     "query": "SELECT max(\"p99\") FROM \"invocation.success.histogram\" WHERE (\"env\" =~ /^$env$/ AND \"scenario\" =~ /^$scenarioName$/) AND $timeFilter GROUP BY time($interval), \"scenario\", \"serviceName\" fill(null)",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
     ]
    },
    {
     "alias": "[[tag_scenario]] - [[tag_serviceName]] (instanceId [[tag_instanceId]])",
     "query": "SELECT max(\"p99\") FROM \"invocation.success.histogram\" WHERE (\"env\" =~ /^$env$/ AND \"scenario\" =~ /^$scenarioName$/) AND $timeFilter GROUP BY time($interval), \"scenario\", \"serviceName\", \"instanceId\" fill(null)"
    }
   ]
  },
  {
   "title": "Response 2xx - max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - (all)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "serviceName" ], "type": "tag" },
      { "params": [ "instanceId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "service.OK.histogram",
     "query": "SELECT max(\"max\") FROM \"invocation.success.histogram\" WHERE (\"env\" =~ /^$env$/ AND \"scenario\" =~ /^$scenarioName$/) AND $timeFilter GROUP BY time($interval), \"scenario\", \"serviceName\" fill(null)",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
     ]
    },
    {
     "alias": "[[tag_scenario]] - [[tag_serviceName]] (instanceId [[tag_instanceId]])",
     "query": "SELECT max(\"max\") FROM \"invocation.success.histogram\" WHERE (\"env\" =~ /^$env$/ AND \"scenario\" =~ /^$scenarioName$/) AND $timeFilter GROUP BY time($interval), \"scenario\", \"serviceName\", \"instanceId\" fill(null)"
    }
   ]
  },
  {
   "title": "Response 4/5xx - median",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - (all)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "serviceName" ], "type": "tag" },
      { "params": [ "instanceId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "service.FAIL.histogram",
     "query": "SELECT max(\"p50\") FROM \"invocation.failure.histogram\" WHERE (\"env\" =~ /^$env$/ AND \"scenario\" =~ /^$scenarioName$/) AND $timeFilter GROUP BY time($interval), \"scenario\", \"serviceName\" fill(null)",
     "select": [
      [
       { "params": [ "p50" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
     ]
    },
    {
     "alias": "[[tag_scenario]] - [[tag_serviceName]] (instanceId [[tag_instanceId]])",
     "query": "SELECT max(\"p50\") FROM \"invocation.failure.histogram\" WHERE (\"env\" =~ /^$env$/ AND \"scenario\" =~ /^$scenarioName$/) AND $timeFilter GROUP BY time($interval), \"scenario\", \"serviceName\", \"instanceId\" fill(null)"
    }
   ]
  },
  {
   "title": "Response 4/5xx - 99th percentile",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - (all)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "serviceName" ], "type": "tag" },
      { "params": [ "instanceId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "service.FAIL.histogram",
     "query": "SELECT max(\"p99\") FROM \"invocation.failure.histogram\" WHERE (\"env\" =~ /^$env$/ AND \"scenario\" =~ /^$scenarioName$/) AND $timeFilter GROUP BY time($interval), \"scenario\", \"serviceName\" fill(null)",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
     ]
    },
    {
     "alias": "[[tag_scenario]] - [[tag_serviceName]] (instanceId [[tag_instanceId]])",
     "query": "SELECT max(\"p99\") FROM \"invocation.failure.histogram\" WHERE (\"env\" =~ /^$env$/ AND \"scenario\" =~ /^$scenarioName$/) AND $timeFilter GROUP BY time($interval), \"scenario\", \"serviceName\", \"instanceId\" fill(null)"
    }
   ]
  },
  {
   "title": "Response 4/5xx - max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - (all)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "serviceName" ], "type": "tag" },
      { "params": [ "instanceId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "service.FAIL.histogram",
     "query": "SELECT max(\"max\") FROM \"invocation.failure.histogram\" WHERE (\"env\" =~ /^$env$/ AND \"scenario\" =~ /^$scenarioName$/) AND $timeFilter GROUP BY time($interval), \"scenario\", \"serviceName\" fill(null)",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
     ]
    },
    {
     "alias": "[[tag_scenario]] - [[tag_serviceName]] (instanceId [[tag_instanceId]])",
     "query": "SELECT max(\"max\") FROM \"invocation.failure.histogram\" WHERE (\"env\" =~ /^$env$/ AND \"scenario\" =~ /^$scenarioName$/) AND $timeFilter GROUP BY time($interval), \"scenario\", \"serviceName\", \"instanceId\" fill(null)"
    }
   ]
  },
  {
   "title": "External services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Services - median OK",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_serviceName]] (instanceId [[tag_instanceId]])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "serviceName" ], "type": "tag" },
      { "params": [ "instanceId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "service.OK.histogram",
     "select": [
      [
       { "params": [ "p50" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
     ]
    }
   ]
  },
  {
   "title": "Services - 99th percentile OK",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_serviceName]] (instanceId [[tag_instanceId]])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "serviceName" ], "type": "tag" },
      { "params": [ "instanceId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "service.OK.histogram",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
     ]
    }
   ]
  },
  {
   "title": "Services - throughput OK",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_serviceName]]",
     "query": "SELECT sum(mean)\nFROM (\n  SELECT mean(value)\n  FROM \"service.OK.instantRate\"\n  WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), scenario, serviceName, instanceId\n)\nGROUP BY time($__interval), scenario, serviceName"
    }
   ]
  },
  {
   "title": "Services - median FAIL",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_serviceName]] (instanceId [[tag_instanceId]])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "serviceName" ], "type": "tag" },
      { "params": [ "instanceId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "service.FAIL.histogram",
     "select": [
      [
       { "params": [ "p50" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
     ]
    }
   ]
  },
  {
   "title": "Services - 99th percentile FAIL",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "[[tag_scenario]] - [[tag_serviceName]] (instanceId [[tag_instanceId]])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "scenario" ], "type": "tag" },
      { "params": [ "serviceName" ], "type": "tag" },
      { "params": [ "instanceId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "service.FAIL.histogram",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "scenario", "operator": "=~", "value": "/^$scenarioName$/" }
     ]
    }
   ]
  },
  {
   "title": "Services - throughput FAIL",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "alias": "$tag_scenario - $tag_serviceName",
     "query": "SELECT sum(mean)\nFROM (\n  SELECT mean(value)\n  FROM \"service.FAIL.instantRate\"\n  WHERE scenario =~ /^$scenarioName$/ AND env = '$env' AND $timeFilter\n  GROUP BY time($__interval), scenario, serviceName, instanceId\n)\nGROUP BY time($__interval), scenario, serviceName"
    }
   ]
  }
 ]
}