apiVersion: v2
name: nussknacker
version: 0.1.5-SNAPSHOT
description: Nussknacker - a design, development, and deployment tool for stream processing
home: https://nussknacker.io/
icon: https://raw.githubusercontent.com/TouK/nussknacker/staging/docs/img/nussknacker_logo_256_b.png
keywords:
  - flink
  - kafka
  - event stream
  - stream processing
  - event stream processing
type: application
appVersion: 0.5.0-release_1.0-2021-09-13-3989-2e6cdbfef0a7b0ffa946f1b2bd69bc1e61c0aadc-SNAPSHOT

dependencies:
  - name: postgresql
    version: 8.6.2
    repository: "@stable"
    condition: postgresql.enabled
  - name: kafka
    version: ^0.21.2
    repository: "@incubator"
    condition: kafka.enabled
  - name: schema-registry
    version: ^1.1.9
    repository: "@incubator"
    condition: schema-registry.enabled
  - name: flink
    version: 0.2.0
    repository: "@riskfocus"
    condition: flink.enabled
  - name: grafana
    version: ^5.7.2
    repository: "@grafana"
    condition: grafana.enabled
  - name: influxdb
    version: ^4.8.6
    repository: "@influxdata"
    condition: influxdb.enabled
  - name: telegraf
    version: ^1.7.27
    repository: "@influxdata"
    condition: telegraf.enabled
  - name: hermes
    version: ^0.3.2
    repository: "@touk"
    condition: hermes.enabled

