apiVersion: v2
name: nussknacker
# In the main branch it should be always the -SNAPSHOT version. Release versions should be on the tags only
version: 1.15.0
description: Nussknacker - a design, development, and deployment tool for stream processing
home: https://nussknacker.io/
icon: https://nussknacker.io/wp-content/uploads/2021/10/Nussknacker-short-black.svg
keywords:
  - flink
  - kafka
  - event stream
  - stream processing
  - event stream processing
type: application
# latest-staging version is used when someone run the snapshot build of this chart manually. scala_2.12 is because it can be used with Flink
# During release it is replaced by the released image version. In the main we should always keep this version
# TODO The best would be to publish X.Y.Z-latest docker image version in core and use it here to make it more explicit
appVersion: 1.15.0
dependencies:
  - name: postgresql
    version: ~12.1.15
    repository: "@bitnami"
    condition: postgresql.enabled
  - name: kafka
    version: ~22.1.6
    repository: "@bitnami"
    condition: kafka.enabled
  - name: zookeeper
    version: ~11.0.3
    repository: "@bitnami"
    condition: zookeeper.enabled
  - name: apicurio-registry
    repository: "@touk"
    version: ~0.1.5
    condition: apicurio-registry.enabled
  - name: flink
    version: ~0.2.0
    repository: "@riskfocus"
    condition: flink.enabled
  - name: grafana
    # Grafana has quite good compatibility between minor version so this should be ok
    version: ^6.51.1
    repository: "@grafana"
    condition: grafana.enabled
  - name: influxdb
    version: ~4.12.5
    repository: "@influxdata"
    condition: influxdb.enabled
  - name: telegraf
    version: ~1.8.34
    repository: "@influxdata"
    condition: telegraf.enabled
