apiVersion: v2
name: nussknacker
version: 1.7.0
description: Nussknacker - a design, development, and deployment tool for stream processing
home: https://nussknacker.io/
icon: https://nussknacker.io/wp-content/uploads/2021/10/Nussknacker-short-black.svg
keywords:
  - flink
  - kafka
  - event stream
  - stream processing
  - event stream processing
type: application
appVersion: 1.7.0
dependencies:
  - name: postgresql
    version: ~11.6.26
    repository: "@bitnami"
    condition: postgresql.enabled
  - name: zookeeper
    version: ~9.2.7
    repository: "@bitnami"
    condition: kafka.enabled
  - name: kafka
    version: ~17.2.6
    repository: "@bitnami"
    condition: kafka.enabled
  - name: apicurio-registry
    repository: "@touk"
    version: ~0.1.5
    condition: apicurio-registry.enabled
  - name: flink
    version: ~0.2.0
    repository: "@riskfocus"
    condition: flink.enabled
  - name: grafana
    # Grafana has quite good compatibility between minor version so this should be ok
    version: ^6.48.0
    repository: "@grafana"
    condition: grafana.enabled
  - name: influxdb
    version: ~4.12.0
    repository: "@influxdata"
    condition: influxdb.enabled
  - name: telegraf
    version: ~1.8.23
    repository: "@influxdata"
    condition: telegraf.enabled
