apiVersion: v2
name: nussknacker
version: 0.1.3-SNAPSHOT
description: A Helm chart for Nussknacker
type: application
appVersion: 0.3.0

dependencies:
  - name: postgresql
    version: 8.6.2
    repository: "@stable"
    condition: postgresql.enabled
  - name: kafka
    version: ^0.21.2
    repository: "@incubator"
    condition: kafka.enabled
  - name: schema-registry
    version: ^1.1.9
    repository: "@incubator"
    condition: schema-registry.enabled
  - name: flink
    version: 0.1.19
    repository: "@riskfocus"
    condition: flink.enabled
  - name: grafana
    version: ^5.7.2
    repository: "@grafana"
    condition: grafana.enabled
  - name: influxdb
    version: ^4.8.6
    repository: "@influxdata"
    condition: influxdb.enabled
  - name: telegraf
    version: ^1.7.27
    repository: "@influxdata"
    condition: telegraf.enabled
  - name: hermes
    version: ^0.3.1
    repository: "@touk"
    condition: hermes.enabled

