apiVersion: v2
name: nussknacker
version: 1.2.2-SNAPSHOT
description: Nussknacker - a design, development, and deployment tool for stream processing
home: https://nussknacker.io/
icon: https://nussknacker.io/wp-content/uploads/2021/10/Nussknacker-short-black.svg
keywords:
  - flink
  - kafka
  - event stream
  - stream processing
  - event stream processing
type: application
appVersion: 1.2.0
dependencies:
  - name: postgresql
    version: 10.12.3
    repository: "@bitnami"
    condition: postgresql.enabled
  - name: kafka
    version: 14.2.0
    repository: "@bitnami"
    condition: kafka.enabled
  - name: apicurio-registry
    repository: "@touk"
    version: 0.1.3
    condition: apicurio-registry.enabled
  - name: flink
    version: 0.2.0
    repository: "@riskfocus"
    condition: flink.enabled
  - name: grafana
    version: ^6.16.13
    repository: "@grafana"
    condition: grafana.enabled
  - name: influxdb
    version: ^4.10.0
    repository: "@influxdata"
    condition: influxdb.enabled
  - name: telegraf
    version: ^1.8.5
    repository: "@influxdata"
    condition: telegraf.enabled
  - name: hermes
    version: ^0.5.4
    repository: "@touk"
    condition: hermes.enabled

